apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nonamesec
  region: us-west-1
vpc:
  subnets:
    private:
      us-west-1c: { id: subnet-00328a78b9d66aa6c }
      us-west-1a: { id: subnet-0bdb7e45a28bcb3c3 }

nodeGroups:
  - name: noname-engines
    instanceType: m5.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 40
    privateNetworking: true

#fargateProfiles:
#  - name: nonamesec-default
#    selectors:
#      - namespace: nonamesec-default

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest

