name: Deploy to EKS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [sandbox, pre-prod, prod]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1

    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
        aws-region: us-west-1

    - name: Deploy to EKS
      run: |
        kubectl config use-context arn:aws:eks:<AWS_REGION>:<AWS_ACCOUNT_ID>:cluster/<EKS_CLUSTER_NAME>
        kustomize build ./k8s/${{ matrix.environment }} | kubectl apply -f -
        helm upgrade --install my-app ./helm/my-app -f ./${{ matrix.environment }}/chart.yaml
