name: EKS Nodegroup Scheduler

on:
  schedule:
    #- cron: '0 21 * * 1-5' # 9:00 PM UTC (5:00 PM EST) - Stop nodes, Mon-Fri
    #- cron: '0 13 * * 1-5' # 1:00 PM UTC (9:00 AM EST) - Start nodes, Mon-Fri

jobs:
  manage-nodegroups:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [sandbox, non-prod]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets['AWS_ROLE_' + matrix.environment] }}
        aws-region: us-east-1

    - name: Install eksctl
      run: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin

    - name: Manage EKS Nodegroups
      env:
        EKS_CLUSTER_NAME: nonamesec
        NODEGROUP_NAME: ${{ secrets['NODEGROUP_NAME_' + matrix.environment] }}
      run: |
        HOUR=$(date +'%H')
        if [ "$HOUR" -eq 21 ]; then
          # Stop nodes at 5:00 PM EST
          eksctl scale nodegroup --cluster=$EKS_CLUSTER_NAME --name=$NODEGROUP_NAME --nodes=0
        elif [ "$HOUR" -eq 13 ]; then
          # Start nodes at 9:00 AM EST
          eksctl scale nodegroup --cluster=$EKS_CLUSTER_NAME --name=$NODEGROUP_NAME --nodes-min=1 --nodes=1
        fi
